language: java
before_install:
  - wget http://dl.google.com/android/android-sdk_r22.0.1-linux.tgz
  - tar -zxf android-sdk_r22.0.1-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/17.0.0
  - echo y | android update sdk --no-ui --filter 1,2,4,5,6 --force
  - sudo apt-get install tree
  - tree ${ANDROID_HOME}
