language: java

before_install:
  # Work around issues with 64 bit
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi

  # Get the SDK
  - wget http://dl.google.com/android/android-sdk_r22.0.1-linux.tgz
  - tar -zxf android-sdk_r22.0.1-linux.tgz

  # Set up required environment
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/17.0.0
  - ln -s ${ANDROID_HOME}/build-tools/17.0.0/aapt ${ANDROID_HOME}/platform-tools/aapt
  - ln -s ${ANDROID_HOME}/build-tools/17.0.0/lib ${ANDROID_HOME}/platform-tools/lib
  - ln -s ${ANDROID_HOME}/build-tools/17.0.0/aidl ${ANDROID_HOME}/platform-tools/aidl

  # Install the API and SDK bits we need
  - echo y | android update sdk --no-ui --filter platform-tools,android-15,sysimg-15 --force

  # Create and start emulator
  - android list targets
  - echo no | android create avd --force -n test -t android-15 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
    # Make sure the emulator has started before running tests
    - adb wait-for-device

notifications:
  irc: "irc.carlcrowder.com#travis"

install: mvn -e validate
script: mvn -e integration-test
